#!/usr/local/bin/perl

use strict;
use warnings 'all';
use Test::Harness;
use FindBin qw($Bin);

use lib "$Bin/../lib";

$ENV{HARNESS_PERL_SWITCHES} = "-MDevel::Cover";
$ENV{DEVEL_COVER_OPTIONS} = "+ignore,\.t\$";

chdir("$Bin");
my @files = glob("*.t");
runtests(@files);
